# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Check Go Installation
      run: go version

    - name: Get dependencies for web
      run: |
        go get -u ./...
        go mod tidy
      working-directory: ./web  # 确保所有依赖项已下载并且是最新的

    - name: Get dependencies for blog
      run: |
        go get -u ./...
        go mod tidy
      working-directory: ./blog  # 确保所有依赖项已下载并且是最新的

    - name: Build
      run: go build -v
      working-directory: ./blog 

    - name: Test
      run: go test -v
      working-directory: ./web
